### PR TITLE
feat: deploy-please

### PR DESCRIPTION
**Pull request by MathieuVeber**
Screenshot 2024-06-11 at 16 45 59

### CODE REVIEW

**Review by aimeerivers — COMMENTED** [review]
fantastic!

just curious: have you thought about how we will manage deploying to different envrionments?

like for developer-service, how will i know if i'm about to deploy to .dev or to .com ?

**Comment by MathieuVeber** [comment]
> fantastic!
> 
> just curious: have you thought about how we will manage deploying to different envrionments?
> 
> like for developer-service, how will i know if i'm about to deploy to .dev or to .com ?

I was thinking that .dev and .com should always be the same and if we were to have a staging environment it would probably auto-deploy. I'm open to suggestions though 😉

**Comment by aimeerivers** [comment]
nice, i like it!

**Review by aimeerivers — APPROVED** [review]
LGTM

**Pull request merged**
