### PR TITLE
feat(workflows): add `approve-please`

### PR DESCRIPTION
**Pull request by MathieuVeber**

### CODE REVIEW

**Review by aimeerivers — COMMENTED** [review]
amazing, i love it!

have you checked what happens if a PR is missing some required checks? i presume `gh pr review --approve` will fail, but is it clear why?

**Comment by aimeerivers** [comment]
wait, will this even be possible?

the kinds of PRs we want to auto approve are those raised by bots. can a bot approve their own PR? do we need two bots, one to open and one to close?

**Comment by MathieuVeber** [comment]
> amazing, i love it!
> 
> have you checked what happens if a PR is missing some required checks? i presume `gh pr review --approve` will fail, but is it clear why?

Approve doesn't mean merge so it shouldn't fail 🙂

**Comment by MathieuVeber** [comment]
> wait, will this even be possible?
> 
> the kinds of PRs we want to auto approve are those raised by bots. can a bot approve their own PR? do we need two bots, one to open and one to close?

Wait you're right! A PR cannot be approve by its author, I guess this cannot work then...

**Comment by aimeerivers** [comment]
> Wait you're right! A PR cannot be approve by its author, I guess this cannot work then...

what is `hedia-bot-limited`? i saw that mentioned in the options. is that another bot we can use for the approvals?

**Comment by aimeerivers** [comment]
if it helps, this is how i find and approve `hedia-bot` PRs as myself ... there might be some tricks in there you can use.

https://github.com/hedia-team/update-repos/blob/main/merge-prs.sh

**Comment by MathieuVeber** [comment]
> > Wait you're right! A PR cannot be approve by its author, I guess this cannot work then...
> 
> what is `hedia-bot-limited`? i saw that mentioned in the options. is that another bot we can use for the approvals?

I think it's one bot that is used with the translations thing (at least it's part of the [translators team](https://github.com/orgs/hedia-team/teams/translators)) but it could be also that it's just a convenient bot with restricted permissions... :shrug:

It's worth giving it a try, let try to use `hedia-bot` or `hedia-bot-limited` depending on the need

**Comment by MathieuVeber** [comment]
> if it helps, this is how i find and approve `hedia-bot` PRs as myself ... there might be some tricks in there you can use.
> 
> https://github.com/hedia-team/update-repos/blob/main/merge-prs.sh

Thanks but since you are "yourself" everything just works and there is no way I will use a PAT from each of us depending on the actor... It needs to be smarter!

**Comment by aimeerivers** [comment]
oooo, smart choosing of which bot to use, i like it!

**Comment by aimeerivers** [comment]
> there is no way I will use a PAT from each of us

no, i agree, that would be a terrible idea!!

**Review by aimeerivers — APPROVED** [review]
i think this will work .. someone just needs to make the limited PAT with permission to approve PRs and set it in `HEDIA_BOT_LIMITED_GITHUB_PAT` as an organization level secret .. and then robots are ready to take over the world! 🤖

**Pull request merged**
